version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    target-branch: "staging"
    labels:
      - "dependencies"
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    target-branch: "staging"
    labels:
      - "dependencies"
    groups:
      actions:
        patterns:
          - "*"
